/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.model.SkippedBlocksmith', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.SkippedBlocksmith = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.SkippedBlocksmith, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.SkippedBlocksmith.displayName = 'proto.model.SkippedBlocksmith';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.SkippedBlocksmith.prototype.toObject = function(opt_includeInstance) {
  return proto.model.SkippedBlocksmith.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.SkippedBlocksmith} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SkippedBlocksmith.toObject = function(includeInstance, msg) {
  var f, obj = {
    blocksmithpublickey: msg.getBlocksmithpublickey_asB64(),
    popchange: jspb.Message.getFieldWithDefault(msg, 2, "0"),
    blockheight: jspb.Message.getFieldWithDefault(msg, 3, 0),
    blocksmithindex: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.SkippedBlocksmith}
 */
proto.model.SkippedBlocksmith.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.SkippedBlocksmith;
  return proto.model.SkippedBlocksmith.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.SkippedBlocksmith} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.SkippedBlocksmith}
 */
proto.model.SkippedBlocksmith.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBlocksmithpublickey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readInt64String());
      msg.setPopchange(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBlockheight(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBlocksmithindex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.SkippedBlocksmith.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.SkippedBlocksmith.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.SkippedBlocksmith} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SkippedBlocksmith.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBlocksmithpublickey_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getPopchange();
  if (parseInt(f, 10) !== 0) {
    writer.writeInt64String(
      2,
      f
    );
  }
  f = message.getBlockheight();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getBlocksmithindex();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional bytes BlocksmithPublicKey = 1;
 * @return {!(string|Uint8Array)}
 */
proto.model.SkippedBlocksmith.prototype.getBlocksmithpublickey = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes BlocksmithPublicKey = 1;
 * This is a type-conversion wrapper around `getBlocksmithpublickey()`
 * @return {string}
 */
proto.model.SkippedBlocksmith.prototype.getBlocksmithpublickey_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBlocksmithpublickey()));
};


/**
 * optional bytes BlocksmithPublicKey = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBlocksmithpublickey()`
 * @return {!Uint8Array}
 */
proto.model.SkippedBlocksmith.prototype.getBlocksmithpublickey_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBlocksmithpublickey()));
};


/** @param {!(string|Uint8Array)} value */
proto.model.SkippedBlocksmith.prototype.setBlocksmithpublickey = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional int64 POPChange = 2;
 * @return {string}
 */
proto.model.SkippedBlocksmith.prototype.getPopchange = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, "0"));
};


/** @param {string} value */
proto.model.SkippedBlocksmith.prototype.setPopchange = function(value) {
  jspb.Message.setProto3StringIntField(this, 2, value);
};


/**
 * optional uint32 BlockHeight = 3;
 * @return {number}
 */
proto.model.SkippedBlocksmith.prototype.getBlockheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.model.SkippedBlocksmith.prototype.setBlockheight = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 BlocksmithIndex = 4;
 * @return {number}
 */
proto.model.SkippedBlocksmith.prototype.getBlocksmithindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.model.SkippedBlocksmith.prototype.setBlocksmithindex = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


goog.object.extend(exports, proto.model);
